### ISSUE TITLE
v1.2.1 Alpha Task List

### ISSUE THREAD

**Issue by TheHeadmaster** [TheHeadmaster/Quartz#12]
- [x] Create new branch
- [x] Bump readme latest commit badge version
- [x] Bump assembly version
- [x] Bump Gitmoji changelog version
- [x] Open pull request
- [x] Implement issue fixes
- [x] Implement planned features
- [x] Conduct testing
- [x] Cleanup changelog
- [x] Final changelog commit
- [x] Add changelog items to pull request
- [x] Ensure passing checks
- [x] Merge pull request
- [x] Close branch
- [x] Close milestone
- [x] Create new release tag
- [x] Add changelog items to new release tag
- [x] Upload installer to new release
- [x] Create embed link to new release on Discord
- [x] Update forum thread on Pokecommunity
