### ISSUE TITLE
v1.2.2 Alpha Task List

### ISSUE THREAD

**Issue by TheHeadmaster** [TheHeadmaster/Quartz#18]
- [x] Bump readme latest commit badge version
- [x] Create new branch
- [x] Bump assembly version
- [x] Bump Gitmoji changelog version
- [x] Open pull request
- [ ] Implement issue fixes
- [ ] Implement planned features
- [ ] Conduct testing
- [ ] Cleanup changelog
- [ ] Final changelog commit
- [ ] Add changelog items to pull request
- [ ] Ensure passing checks
- [ ] Merge pull request
- [ ] Close branch
- [ ] Close milestone
- [ ] Create new release tag
- [ ] Add changelog items to new release tag
- [ ] Upload installer to new release
- [ ] Create embed link to new release on Discord
- [ ] Update forum thread on Pokecommunity
