### ISSUE TITLE
v1.1.3 Alpha Task List

### ISSUE THREAD

**Issue by TheHeadmaster** [TheHeadmaster/Quartz#5]
- [x] Create new branch
- [x] Bump assembly version
- [x] Bump Gitmoji changelog version
- [x] Implement issue fixes
- [x] Implement planned features
- [x] Conduct testing
- [x] Cleanup changelog
- [x] Final changelog commit
- [x] Open pull request
- [x] Add changelog items to pull request
- [x] Ensure passing checks
- [x] Merge pull request
- [x] Close branch
- [x] Create new release tag
- [x] Add changelog items to new release tag
- [x] Upload installer to new release
- [x] Create embed link to new release on Discord
- [x] Update forum thread on Pokecommunity
